config/routes.rb
Birds::Application.routes.draw do
  resources :cards


  resources :birds


  # scaffold resources
    resources :authorizations
    resources :users

  get "welcome/index"

  root :to => 'welcome#index'

  match '/image', :to => 'birds#image'
  post "/new_location" => "user#new_location"

  #omniauth
    get   '/login', :to => 'sessions#new', :as => :login
    match '/auth/:provider/callback', :to => 'sessions#create'
    match '/auth/failure', :to => 'sessions#failure'
    get '/logout', :to => 'sessions#destroy', :as => :logout

end

app/models/bird.rb
class Bird < ActiveRecord::Base
  attr_accessible :com_name, :sci_name, :image_url
  has_many :cards

  def set_and_return_image_url
    unless self.image_url
      self.image_url = Google::Search::Image.new(:query => self.com_name).first.uri
      self.save
    end

    self.image_url
  end
end

app/controllers/birds_controller.rb
class BirdsController < ApplicationController
  # GET /birds
  # GET /birds.json
  before_filter :check_admin
  
  def index
    @birds = Bird.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @birds }
    end
  end

  # GET /birds/1
  # GET /birds/1.json
  def show
    @bird = Bird.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bird }
    end
  end

  # GET /birds/new
  # GET /birds/new.json
  def new
    @bird = Bird.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bird }
    end
  end

  # GET /birds/1/edit
  def edit
    @bird = Bird.find(params[:id])
  end

  # POST /birds
  # POST /birds.json
  def create
    @bird = Bird.new(params[:bird])

    respond_to do |format|
      if @bird.save
        format.html { redirect_to @bird, notice: 'Bird was successfully created.' }
        format.json { render json: @bird, status: :created, location: @bird }
      else
        format.html { render action: "new" }
        format.json { render json: @bird.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /birds/1
  # PUT /birds/1.json
  def update
    @bird = Bird.find(params[:id])

    respond_to do |format|
      if @bird.update_attributes(params[:bird])
        format.html { redirect_to @bird, notice: 'Bird was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bird.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /birds/1
  # DELETE /birds/1.json
  def destroy
    @bird = Bird.find(params[:id])
    @bird.destroy

    respond_to do |format|
      format.html { redirect_to birds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/birds_helper.rb
module BirdsHelper
end

app/views/birds/_form.html.erb
<%= form_for(@bird) do |f| %>
  <% if @bird.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bird.errors.count, "error") %> prohibited this bird from being saved:</h2>

      <ul>
      <% @bird.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :com_name %><br />
    <%= f.text_field :com_name %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/birds/edit.html.erb
<h1>Editing bird</h1>

<%= render 'form' %>

<%= link_to 'Show', @bird %> |
<%= link_to 'Back', birds_path %>

app/views/birds/index.html.erb
<h1>Listing birds</h1>

<table>
  <tr>
    <th>Com name</th>
    <th>Image url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @birds.each do |bird| %>
  <tr>
    <td><%= bird.com_name %></td>
    <td><%= bird.image_url %></td>
    <td><%= link_to 'Show', bird %></td>
    <td><%= link_to 'Edit', edit_bird_path(bird) %></td>
    <td><%= link_to 'Destroy', bird, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bird', new_bird_path %>

app/views/birds/new.html.erb
<h1>New bird</h1>

<%= render 'form' %>

<%= link_to 'Back', birds_path %>

app/views/birds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Com name:</b>
  <%= @bird.com_name %>
</p>

<p>
  <b>Image url:</b>
  <%= @bird.image_url %>
</p>


<%= link_to 'Edit', edit_bird_path(@bird) %> |
<%= link_to 'Back', birds_path %>