config/routes.rb
Birds::Application.routes.draw do
  resources :cards


  resources :birds


  # scaffold resources
    resources :authorizations
    resources :users

  get "welcome/index"

  root :to => 'welcome#index'

  match '/image', :to => 'birds#image'
  post "/new_location" => "user#new_location"

  #omniauth
    get   '/login', :to => 'sessions#new', :as => :login
    match '/auth/:provider/callback', :to => 'sessions#create'
    match '/auth/failure', :to => 'sessions#failure'
    get '/logout', :to => 'sessions#destroy', :as => :logout

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  attr_accessible :access_token, :oauth_token_secret, :provider, :refresh_token, :uid, :user_id
  belongs_to :user
  after_create :update_cards

  def self.find_or_create(auth_hash)
    auth = Authorization.where(provider:auth_hash["provider"],uid:auth_hash["uid"]).first
    if auth.nil?
        user = User.where(email:auth_hash["info"]["email"]).first_or_create
        auth = Authorization.create(user_id:user.id,provider:auth_hash["provider"],uid:auth_hash["uid"],access_token:auth_hash["credentials"]['token'])
        if auth_hash['credentials']['refresh_token']
          auth.refresh_token = auth_hash['credentials']['refresh_token']
        end
        auth.save
      end
      auth
  end

  def refresh_access_token(uri,client_id,client_secret)
    if self.refresh_token
     begin
      response = HTTParty.post(uri, :body => {refresh_token: self.refresh_token, client_id: client_id, client_secret: client_secret, grant_type:'refresh_token'})
                    self.access_token = response['access_token']
                    self.save
                    return true
    rescue
    end
   end
   return false
  end

  def location
    require "mirror-api"
    begin
      api = Mirror::Api::Client.new(self.access_token)
      if location = api.locations.list.items.first
        return [location.latitude,location.longitude,location.accuracy]
      end
    rescue
      return false
    end
  end

  def delete_all_cards
    require "mirror-api"
    api = Mirror::Api::Client.new(self.access_token)

    while (items = api.timeline.list.items) && items.count > 0
      items.each do |card|
        api.timeline.delete(card.id)
      end  
    end
  end

  def delete_missing_cards(birds)
    require "mirror-api"
    api = Mirror::Api::Client.new(self.access_token)

    com_names = birds.map { |bird| bird['comName']}

    self.user.cards.each do |card|
      puts "considering user's "+card.com_name+" card for deletion..."
      unless com_names.include?(card.com_name)
        puts "  didn't find the card, deleting..."
        api.timeline.delete(card.mirror_id)
        Card.where(com_name:bird['comName'],user_id:self.user.id).destroy_all
      end
    end
  end

  def update_cards
      if location = self.location
        birds = self.user.birds_nearby(location[0],location[1])
        require "mirror-api"
        api = Mirror::Api::Client.new(self.access_token)

        self.delete_missing_cards(birds)

        # add new bird cards
        birds.each do |birdjson|
          puts "deciding on "+birdjson['comName']
          bird = Bird.where(com_name:birdjson['comName'],sci_name:birdjson['sciName']).first_or_create
          unless Card.where(bird_id:bird.id,user_id:self.user.id).count > 0
            puts "adding card for "+birdjson['comName']
            card = Card.create(com_name:bird.com_name,bird_id:bird.id,user_id:self.user.id)
            card.insert_card(birdjson)
          end
        end
      end
  end
end 

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController
  # GET /authorizations
  # GET /authorizations.json
  before_filter :check_admin
  
  def index
    @authorizations = Authorization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authorizations }
    end
  end

  # GET /authorizations/1
  # GET /authorizations/1.json
  def show
    @authorization = Authorization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @authorization }
    end
  end

  # GET /authorizations/new
  # GET /authorizations/new.json
  def new
    @authorization = Authorization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @authorization }
    end
  end

  # GET /authorizations/1/edit
  def edit
    @authorization = Authorization.find(params[:id])
  end

  # POST /authorizations
  # POST /authorizations.json
  def create
    @authorization = Authorization.new(params[:authorization])

    respond_to do |format|
      if @authorization.save
        format.html { redirect_to @authorization, notice: 'Authorization was successfully created.' }
        format.json { render json: @authorization, status: :created, location: @authorization }
      else
        format.html { render action: "new" }
        format.json { render json: @authorization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authorizations/1
  # PUT /authorizations/1.json
  def update
    @authorization = Authorization.find(params[:id])

    respond_to do |format|
      if @authorization.update_attributes(params[:authorization])
        format.html { redirect_to @authorization, notice: 'Authorization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @authorization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authorizations/1
  # DELETE /authorizations/1.json
  def destroy
    @authorization = Authorization.find(params[:id])
    @authorization.destroy

    respond_to do |format|
      format.html { redirect_to authorizations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/authorizations_helper.rb
module AuthorizationsHelper
end

app/views/authorizations/_form.html.erb
<%= form_for(@authorization) do |f| %>
  <% if @authorization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authorization.errors.count, "error") %> prohibited this authorization from being saved:</h2>

      <ul>
      <% @authorization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :provider %><br />
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authorizations/edit.html.erb
<h1>Editing authorization</h1>

<%= render 'form' %>

<%= link_to 'Show', @authorization %> |
<%= link_to 'Back', authorizations_path %>

app/views/authorizations/index.html.erb
<h1>Listing authorizations</h1>

<table>
  <tr>
    <th>Provider</th>
    <th>Uid</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authorizations.each do |authorization| %>
  <tr>
    <td><%= authorization.provider %></td>
    <td><%= authorization.uid %></td>
    <td><%= authorization.user_id %></td>
    <td><%= link_to 'Show', authorization %></td>
    <td><%= link_to 'Edit', edit_authorization_path(authorization) %></td>
    <td><%= link_to 'Destroy', authorization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Authorization', new_authorization_path %>

app/views/authorizations/new.html.erb
<h1>New authorization</h1>

<%= render 'form' %>

<%= link_to 'Back', authorizations_path %>

app/views/authorizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Provider:</b>
  <%= @authorization.provider %>
</p>

<p>
  <b>Uid:</b>
  <%= @authorization.uid %>
</p>

<p>
  <b>User:</b>
  <%= @authorization.user_id %>
</p>

<%= link_to 'Edit', edit_authorization_path(@authorization) %> |
<%= link_to 'Back', authorizations_path %>